name: MLflow CI - Build Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install mlflow pandas scikit-learn

    - name: Run training with MLflow
      run: |
        python MLProject/modelling.py

    - name: Build Docker Image with MLflow
      run: |
        RUN_ID=$(cat run_id.txt)
        mlflow models build-docker \
          -m runs:/$RUN_ID/model \
          -n ${{ secrets.DOCKER_USERNAME }}/insurance-mlflow

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/insurance-mlflow